### ISSUE TITLE
Crear Modelo Usuario

### ISSUE THREAD

**Issue by rrodriguezgon** [MirionsDevTeam/event-planning-back#11]
Como equipo técnico necesitamos crear el modelo/tabla de **Usuario** con los siguientes campos:

id - int **(PK) [Primary Key]** - Clave primaria - autoincrement - required
email - varchar(50) - unique - required
nombre - varchar(50)  - required
nick - varchar(50) - unique - required
password - varchar(50) - encrypt - required
fecha_de_nac. - date
imagen_url - varchar(50)
teléfono - number
población - varchar(50)
observaciones - varchar(255)
fecha_creacion - datetime  - required
usuario_creacion - int (idUsuario) - required
fecha_modificacion -datetime
usuario_modificacion - int (idUsuario)
fecha_eliminacion - datetime 
usuario_eliminacion - int (idUsuario)

Para poder posteriormente crear la estructura de backend y poder realizar un CRUD sobre la misma y poder utilizarla desde Frontend.

**Comment by RafaM88** [comment]
Algunos apuntes sobre algunos campos:
-Teléfono: mejor usar string. En caso de tener que poner prefijos, o números extranjeros con guiones. Mejor usar cadena de texto y controlarla con regex.
-¿Incluimos campos provincia y código postal (al menos provincia sería interesante)?
-usuario_creacion, usuario_modificacion y usuario_eliminacion, ¿pueden ser claves foráneas con recursividad y cardinalidad (0,1)? usuario_creacion no porque es obligatorio, y es (1,1), pero las otras sí pueden ser (0,1).

**Comment by RafaM88** [comment]
[https://github.com/frontid/ComunidadesProvinciasPoblaciones/blob/master/arbol.json](url)
Dejo este enlace de un json con todas las comunidades autónomas, localidades y provincias de España. Puede ser útil en la zona de registro, para elegir la localidad.
