### ISSUE TITLE
Crear Modelo Evento

### ISSUE THREAD

**Issue by rrodriguezgon** [MirionsDevTeam/event-planning-back#12]
**Como equipo técnico necesitamos** crear el modelo/tabla de **Evento** con los siguientes campos:

id - int/number **(PK)** [Primary Key] - Clave primaria
titulo - string/varchar(50)
descripcion - string/varchar(255) 
ubicacion - string/varchar(255)
fecha_evento - string/date/datetime
tipo_evento - string/varchar(50)
invitados_min - int/number (PK)
invitados_max - int/number (PK)
observaciones - string/varchar(255)
fecha_creacion - string/date/datetime
usuario_creacion - int/number (idUsuario)
fecha_modificacion - string/date/datetime 
usuario_modificacion - int/number (idUsuario)  
fecha_eliminacion - string/date/datetime
usuario_eliminacion - int/number (idUsuario)

**Para poder** posteriormente crear la estructura de backend y poder realizar un CRUD sobre la misma y poder utilizarla desde Frontend.

**Comment by RafaM88** [comment]
Hago pequeñas modificaciones en el modelo.
- Desgloso la ubicación en Provincias, localidades y dirección, para en un futuro, tener unificada la información y poder filtrar por provincias y localidades.
- Añado campo coordenadas (puede ser nulo) si es un evento en una ubicación complicada y se quieren poner coordenada
